import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar/Navbar";
import Footer from "@/components/Layout/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar></Navbar>
        </header>
        <div className="h-[calc(100vh-120px)]">
          {children}
          </div>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
